name: Deploy Gateway Infra

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  EKS_CLUSTER_NAME: hack-infra-eks

jobs:
  deploy-infra:
    name: Apply Kong & Plugins
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Configura Credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      # 2. Conecta o kubectl ao cluster EKS
      - name: Update Kube Config
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      # 3. Aplica os manifestos na ordem correta
      - name: Apply Kubernetes Manifests
        run: |
          echo "Deploying Kong Ingress Controller..."
          
          # Primeiro aplicamos a instalação base (Namespace, CRDs, Controller)
          kubectl apply -f k8s/kong-installation.yaml
          
          # Aguarda um pouco para garantir que os CRDs (Custom Resource Definitions) foram registrados
          # Isso evita erro ao tentar aplicar os plugins logo em seguida
          echo "Waiting for CRDs..."
          sleep 10
          
          echo "Deploying Global Plugins..."
          # Aplica a pasta de plugins inteira (CORS, Rate Limit, etc.)
          kubectl apply -f k8s/plugins/
          
          echo "Gateway Infrastructure Updated!"